### ISSUE TITLE
Version 0.4.0 plan

### ISSUE THREAD

**Issue by greyli** [greyli/apiflask#24]
Expected release date: 2021/4/20

Features:

- [x] Remove unnecessary configuration variables
- [x] Multiple response/request examples support
- [x] Rename `abort_json()` to `abort()`

More docs:

- [x] Configuration
- [x] Comparison
- [x] Docs Index

Changelog: https://apiflask.com/changelog/#version-040
Next: [Version 0.5.0 plan](https://github.com/greyli/apiflask/issues/25)

**Comment by greyli** [comment]
[Released](https://github.com/greyli/apiflask/releases/tag/0.4.0) at 2021/4/20.
